import { createFileRoute } from "@tanstack/react-router";
import { Clock3, MapPin, Phone, Send } from "lucide-react";
import { useState, type FormEvent } from "react";
import { PageHero } from "@/components/site-shell";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/contacts")({
  head: () => ({ meta: [{ title: "Контакты сервиса RR-STAB" }, { name: "description", content: "Адрес, телефон и форма записи в сервис активных стабилизаторов Range Rover." }, { property: "og:title", content: "Контакты RR-STAB" }, { property: "og:description", content: "Свяжитесь с сервисом RR-STAB и запишитесь на диагностику." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/contacts" }] }),
  component: ContactsPage,
});
function ContactsPage(){const[sent,setSent]=useState(false); const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSent(true)}; return <><PageHero eyebrow="Связаться с нами" title="Запишитесь на диагностику" text="Опишите симптомы — специалист уточнит детали, сориентирует по стоимости и предложит удобное время."/><section className="industrial-grid py-14 sm:py-20"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-2"><div className="space-y-4">{[[Phone,"Телефон","+7 911 923-47-91"],[MapPin,"Адрес","Санкт-Петербург, ул. Седова, 12"],[Clock3,"Режим работы","Пн–Сб, 09:00–19:00"]].map(([Icon,label,value])=>{const ContactIcon=Icon as typeof Phone; return <div key={label as string} className="flex gap-4 border-b border-border py-5"><ContactIcon className="size-7 text-primary"/><div><p className="text-xs font-bold uppercase text-muted-foreground">{label as string}</p><p className="mt-1 text-xl font-black">{value as string}</p></div></div>})}</div><div className="rounded border border-border bg-card p-6 sm:p-8">{sent?<div className="grid min-h-72 place-items-center text-center"><div><div className="mx-auto grid size-14 place-items-center rounded-full bg-primary text-2xl font-black">✓</div><h2 className="mt-5 text-2xl font-black uppercase">Заявка отправлена</h2><p className="mt-2 text-muted-foreground">Мы перезвоним в рабочее время.</p></div></div>:<form onSubmit={submit}><h2 className="text-2xl font-black uppercase">Оставить заявку</h2><div className="mt-6 grid gap-4"><input required aria-label="Имя" className="h-12 rounded-sm border border-input bg-background px-4 outline-none focus:border-primary" placeholder="Ваше имя"/><input required type="tel" aria-label="Телефон" className="h-12 rounded-sm border border-input bg-background px-4 outline-none focus:border-primary" placeholder="Телефон"/><textarea aria-label="Комментарий" className="min-h-28 rounded-sm border border-input bg-background p-4 outline-none focus:border-primary" placeholder="Модель автомобиля и симптомы"/><Button type="submit" variant="service" size="lg">Отправить <Send/></Button></div></form>}</div></div></section></>}